services:
  web:
    extends:
      file: ./backend/docker-compose.yml
      service: web
    env_file:
      - ./backend/.env

  db:
    extends:
      file: ./backend/docker-compose.yml
      service: db
    env_file:
      - ./backend/.env

  redis:
    extends:
      file: ./backend/docker-compose.yml
      service: redis
    env_file:
      - ./backend/.env

  celery:
    extends:
      file: ./backend/docker-compose.yml
      service: celery
    volumes:
      - ${PWD}/backend/src:/app
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend

  cloudbeaver:
    extends:
      file: ./backend/docker-compose.yml
      service: cloudbeaver

volumes:
  pgdata:
  cloudbeaver_data:
  redis_data:

